kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-access
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-full-access
subjects:
- kind: Group
  namespace: dev
  name: 846e6538-c8db-43bb-b016-3bda667c8202
