kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-full-access
  namespace: dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]

# - apiGroups: ["", "extensions", "apps"]
#   resources: ["*"]
#   verbs: ["*"]
# - apiGroups: ["batch"]
#   resources:
#   - jobs
#   - cronjobs
#   verbs: ["*"]
